# Generated by Django 5.0.6 on 2024-05-13 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='Nombre de Producto')),
                ('precioProducto', models.IntegerField(verbose_name='Precio de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='tipoProducto',
            fields=[
                ('idTipoProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Tipo de Producto')),
                ('nombreTipoProducto', models.CharField(max_length=50, unique=True, verbose_name='Nombre de Tipo de Producto')),
                ('descripcionTipoProducto', models.CharField(max_length=50, verbose_name='Descripcion de Tipo de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='stockProducto',
            fields=[
                ('idStockProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de Stock de Producto')),
                ('stockProducto', models.IntegerField(verbose_name='Stock de Producto')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.producto', verbose_name='Id de Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='idTipoProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.tipoproducto', verbose_name='Id de Tipo de Producto'),
        ),
    ]
