# Generated by Django 5.0.6 on 2024-05-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_tipoproducto_nombretipoproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoproducto',
            name='descripcionTipoProducto',
        ),
    ]
