# Generated by Django 5.0.6 on 2024-05-09 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_producto_categoria_delete_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoProducto',
            fields=[
                ('idTipoProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Tipo de Producto')),
                ('nombreTipoProducto', models.CharField(max_length=50, verbose_name='Nombre de Tipo de Producto')),
                ('descripcionTipoProducto', models.CharField(max_length=50, verbose_name='Descripcion de Tipo de Producto')),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='stockProducto',
        ),
        migrations.CreateModel(
            name='stockProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockProducto', models.IntegerField(verbose_name='Stock de Producto')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto', verbose_name='Id de Producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='idTipoProducto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tipoproducto', verbose_name='Id de Tipo de Producto'),
            preserve_default=False,
        ),
    ]
