# Generated by Django 5.0.6 on 2024-05-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tipoproducto_descripciontipoproducto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoproducto',
            name='descripcionTipoProducto',
            field=models.CharField(default=1, max_length=50, verbose_name='Descripcion de Tipo de Producto'),
            preserve_default=False,
        ),
    ]
