# Generated by Django 5.0.6 on 2024-05-13 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_producto_nombreproducto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='idTipoProducto',
        ),
    ]
