# Generated by Django 5.0.6 on 2024-05-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_producto_nombreproducto_producto_tipoproducto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='nombreProducto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='tipoProducto',
        ),
    ]
