# Generated by Django 5.0.6 on 2024-05-13 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_producto_nombreproducto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stockProducto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.stockproducto', verbose_name='Stock de Producto'),
            preserve_default=False,
        ),
    ]
